version: "3.9"
services:
  backend:
    build: ./api
    container_name: api_container
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
      - /app/node_modules
  frontend:
    build: ./myblog
    container_name: myblog_container
    ports:
      - "3000:3000"
    volumes:
      - ./myblog:/app
      - /app/node_modules
    stdin_open: true #Standard input open means that you can type into the container
    tty: true #Teletypewriter is a terminal emulation program that allows you to interact with the container